name: Secure Patching

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  patching:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Patch
        env:
          SUDO_ASKPASS: /github/workspace/askpass.sh
        run: |
          #!/bin/bash
          echo "${{ secrets.TARGET_MACHINE_PASSWORD }}" | sudo -S bash -c '
            set -e  # Exit immediately if any command fails
            # Update package lists and upgrade installed packages
            apt update && apt upgrade -y
            # Sign the kernel modules
            python3 /opt/secureboot/scripts/sign-kernel-modules.py
            # Check Secure Boot state
            mokutil --sb-state
          '
      - name: Print Result
        run: |
          echo "Patching and signing completed (or failed)."
